implement header, staple, and gpt icons
QueueLab/MapGPT pull request #34
Opened 2024-06-10 16:54 UTC by rosaleensiroosi

resolves #32.

2024-06-10 20:45 UTC, ngoiyaeric commented on MapGPT/components/header.tsx
> +          <img src="/images/logo.png" alt="Logo" className="h-6" />
This image should be dynamic, try converting it to an SVG.

2024-06-10 20:46 UTC, ngoiyaeric requested changes
add a screenshot so I can see the positioning and size for the icons.

2024-06-11 04:17 UTC, rosaleensiroosi commented
<img width="1710" alt="image" src="https://github.com/QueueLab/MapGPT/assets/171291607/0cdc4f61-2e42-45d8-8420-608c9c027e1c">

2024-06-11 07:29 UTC, ngoiyaeric commented on MapGPT/components/header.tsx
> +          <img src="/images/logo.png" alt="Logo" className="h-6" />
@rosaleensiroosi https://chatgpt.com/share/1ed13f02-8738-41a2-a8da-76e8eb5a7e06

2024-06-11 08:15 UTC, ngoiyaeric commented
I've also noticed that the logo disappears when there are chats to scroll, its best to have it all the way to the left of the screen and not above the chat. Also if you could arrange the order of the icons as such. 
<img width="840" alt="Screen Shot 2024-06-11 at 11 14 38 AM" src="https://github.com/QueueLab/MapGPT/assets/115367894/75948c00-ee8f-4670-8536-fc8e2959fb64">

2024-06-12 05:14 UTC, merged